- name: AWS CLI | Create .aws dir
  sudo: yes
  sudo_user: "{{ aws_config_user }}"
  file: path="~/.aws" state=directory

- name: AWS CLI | Create config
  sudo: yes
  sudo_user: "{{ aws_config_user }}"
  template: src=config.j2 dest="~/.aws/config" mode=0640
